-- LOS PAQUETES INCLUYEN SERVICIOS FIJOS (Felipe 28-08: "esa es una
-- mala regla, debería incluir los servicios fijos" — el salón y la
-- decoración SON parte del paquete "Graduación solo cóctel").
-- Espejo de service_group_collection_services, para fijos.
CREATE TABLE IF NOT EXISTS public.service_group_collection_fixed_services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id bigint NOT NULL REFERENCES public.service_group_collections(id) ON DELETE CASCADE,
  fixed_service_id bigint NOT NULL REFERENCES public.fixed_services(id) ON DELETE CASCADE,
  quantity numeric NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON public.service_group_collection_fixed_services TO service_role;
