-- Módulo Logística · Fase 1b: catálogos base.
-- suppliers (proveedores), supplies (insumos) y management_resources
-- (recursos de gestión: staff/arriendos). Todos por company_id.
--
-- Unidades (convención Fudo): cada insumo pertenece a una familia
--   masa (kg/gr) · volumen (L/ml) · unidad (enteros o fracciones)
-- y su precio se guarda por unidad base (kg, L o unidad).
-- Los recursos de gestión NO llevan precio fijo: el precio se asigna por
-- evento; last_price guarda solo el último usado como referencia.

CREATE TABLE IF NOT EXISTS public.suppliers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id),
  name text NOT NULL,
  phone text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT suppliers_company_name_unique UNIQUE (company_id, name)
);

CREATE TABLE IF NOT EXISTS public.supplies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id),
  name text NOT NULL,
  unit_family text NOT NULL
    CHECK (unit_family IN ('masa','volumen','unidad')),
  price numeric NOT NULL DEFAULT 0,
  supplier_id bigint REFERENCES public.suppliers(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT supplies_company_name_unique UNIQUE (company_id, name)
);

CREATE TABLE IF NOT EXISTS public.management_resources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id),
  name text NOT NULL,
  type text NOT NULL CHECK (type IN ('personal','arriendo')),
  last_price numeric,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mgmt_resources_company_name_unique UNIQUE (company_id, name)
);

GRANT ALL ON public.suppliers, public.supplies, public.management_resources
  TO anon, authenticated;
