-- Módulo Logística · Fase 2: recetas por servicio.
--
-- furniture_items: mini-catálogo de mobiliario (solo nombre por ahora; la
--   Fase 5 de inventario le agregará foto y cantidades sin rehacer nada).
-- service_recipe_items: líneas de receta de un servicio del catálogo.
--   - service_type/service_id apuntan a variable_services o fixed_services.
--   - item_kind 'insumo' (con supply_id) o 'mobiliario' (con furniture_id).
--   - qty_per_person SIEMPRE por persona; unit pertenece a la familia del
--     insumo (kg/gr · L/ml · u); el mobiliario usa 'u'.
--   - Regla de negocio: servicios variables llevan insumos + mobiliario;
--     los fijos SOLO mobiliario (se aplica en la UI).

CREATE TABLE IF NOT EXISTS public.furniture_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id),
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT furniture_company_name_unique UNIQUE (company_id, name)
);

CREATE TABLE IF NOT EXISTS public.service_recipe_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id),
  service_type text NOT NULL CHECK (service_type IN ('variable','fixed')),
  service_id bigint NOT NULL,
  item_kind text NOT NULL CHECK (item_kind IN ('insumo','mobiliario')),
  supply_id bigint REFERENCES public.supplies(id) ON DELETE CASCADE,
  furniture_id bigint REFERENCES public.furniture_items(id) ON DELETE CASCADE,
  qty_per_person numeric NOT NULL CHECK (qty_per_person > 0),
  unit text NOT NULL CHECK (unit IN ('kg','gr','L','ml','u')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT recipe_item_kind_refs CHECK (
    (item_kind = 'insumo' AND supply_id IS NOT NULL AND furniture_id IS NULL)
    OR
    (item_kind = 'mobiliario' AND furniture_id IS NOT NULL AND supply_id IS NULL)
  )
);

-- Un mismo insumo/mobiliario no puede repetirse dentro de una receta.
CREATE UNIQUE INDEX IF NOT EXISTS recipe_unique_supply
  ON public.service_recipe_items(service_type, service_id, supply_id)
  WHERE supply_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS recipe_unique_furniture
  ON public.service_recipe_items(service_type, service_id, furniture_id)
  WHERE furniture_id IS NOT NULL;

GRANT ALL ON public.furniture_items, public.service_recipe_items
  TO anon, authenticated;
