-- Módulo Logística: recursos con lista de precios de terceros + costo de
-- servicios fijos por referencias.
--
-- Caso real: FL Services publica su lista anual (silla $1.500/persona,
-- fiesta 8 hrs $700.000/evento). Los recursos de gestión ganan proveedor,
-- precio de lista y modo de cobro — todos OPCIONALES: el staff (garzones)
-- puede seguir sin precio (se asigna por evento). El precio de lista es la
-- referencia; en cada evento siempre es editable (premios y rebajas por
-- volumen se resuelven en el evento, el catálogo no se toca).
--
-- El costo de un servicio fijo pasa a ser una lista de REFERENCIAS a
-- recursos (fixed_service_cost_items): al actualizar la lista anual del
-- proveedor, todos los servicios que la referencian se actualizan solos.
-- cost_fixed / cost_per_person (migración 12) quedan como totales cacheados
-- que la app sincroniza al editar líneas.

ALTER TABLE public.management_resources
  ADD COLUMN IF NOT EXISTS supplier_id bigint
    REFERENCES public.suppliers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS list_price numeric,
  ADD COLUMN IF NOT EXISTS charge_mode text NOT NULL DEFAULT 'por_evento'
    CHECK (charge_mode IN ('por_evento','por_persona'));

CREATE TABLE IF NOT EXISTS public.fixed_service_cost_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id),
  fixed_service_id bigint NOT NULL
    REFERENCES public.fixed_services(id) ON DELETE CASCADE,
  resource_id bigint NOT NULL
    REFERENCES public.management_resources(id) ON DELETE CASCADE,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cost_item_unique UNIQUE (fixed_service_id, resource_id)
);

GRANT ALL ON public.fixed_service_cost_items TO anon, authenticated;
