-- Módulo Logística · Fase 3b: provisión POR INSUMO.
-- El abastecimiento real es por partes (martes carnes, miércoles verduras,
-- condimentos al final), así que cada evento registra qué insumos ya están
-- comprados: foto de cantidad (unidad base) y costo al momento de provisionar.
-- Re-provisionar un insumo actualiza su fila (UNIQUE quotation+supply).
-- quotations.provisioned_at (migración 15) pasa a significar "evento completo".

CREATE TABLE IF NOT EXISTS public.event_supply_provisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL,
  quotation_id uuid NOT NULL REFERENCES public.quotations(id) ON DELETE CASCADE,
  supply_id bigint NOT NULL REFERENCES public.supplies(id) ON DELETE CASCADE,
  qty_base numeric NOT NULL,
  cost numeric NOT NULL DEFAULT 0,
  provisioned_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (quotation_id, supply_id)
);

CREATE INDEX IF NOT EXISTS idx_esp_company
  ON public.event_supply_provisions(company_id);
