-- Módulo Logística · Fase 4: recursos por evento + foto de provisión.
--
-- event_resources: asignación de recursos de gestión (staff, arriendos,
-- compras) a un evento concreto. El precio llega precargado desde la lista
-- del catálogo pero es editable por evento (rebajas negociadas; el staff sin
-- precio de lista se valoriza aquí). Costo línea =
-- (price_fixed + price_per_person × personas) × quantity.
--
-- provisioned_people / provisioned_services: foto al provisionar, para
-- advertir si después cambian las personas o los servicios del evento.

CREATE TABLE IF NOT EXISTS public.event_resources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL,
  quotation_id uuid NOT NULL REFERENCES public.quotations(id) ON DELETE CASCADE,
  resource_id bigint NOT NULL REFERENCES public.management_resources(id) ON DELETE CASCADE,
  quantity numeric NOT NULL DEFAULT 1,
  price_fixed numeric NOT NULL DEFAULT 0,
  price_per_person numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_event_resources_q
  ON public.event_resources(quotation_id);

ALTER TABLE public.quotations
  ADD COLUMN IF NOT EXISTS provisioned_people integer,
  ADD COLUMN IF NOT EXISTS provisioned_services jsonb;
