-- Ficha de cocina (Etapa 2 · Operación).
-- Dos datos nuevos por evento, ambos se editan en la pestaña Gestión:
--   event_service_times: horario de cada servicio (desayuno 09:30...)
--   event_kitchen_notes: notas del evento como LISTA (no texto en bloque):
--     "2 alérgicos al maní", "cliente pidió la carne a punto"...
-- La ficha imprimible se genera siempre fresca desde los datos vigentes
-- (cotización + recetas + horarios + notas); no se guarda ningún PDF.

CREATE TABLE IF NOT EXISTS public.event_service_times (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL,
  quotation_id uuid NOT NULL REFERENCES public.quotations(id) ON DELETE CASCADE,
  service_name text NOT NULL,
  start_time text NOT NULL DEFAULT '',
  UNIQUE (quotation_id, service_name)
);

CREATE TABLE IF NOT EXISTS public.event_kitchen_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL,
  quotation_id uuid NOT NULL REFERENCES public.quotations(id) ON DELETE CASCADE,
  note text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ekn_quotation
  ON public.event_kitchen_notes(quotation_id);
