-- Secciones dentro de cada categoría (Entradas / Fondos / Postres...).
-- Como una carta real: cada categoría define SUS propias secciones (las del
-- desayuno no son las del almuerzo). La sección vive en el VÍNCULO
-- servicio-categoría (no en el servicio), porque un servicio multicategoría
-- puede ser "Bebidas" en Almuerzos y "Refrescos" en Coffee.
-- Un servicio recién asignado a una sección entra al final de ella; el
-- arrastre reordena dentro de la sección. Categoría sin secciones = igual
-- que siempre.

CREATE TABLE IF NOT EXISTS public.category_sections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL,
  category_id bigint NOT NULL
    REFERENCES public.service_categories(id) ON DELETE CASCADE,
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (category_id, name)
);

ALTER TABLE public.variable_service_categories
  ADD COLUMN IF NOT EXISTS section_id bigint
    REFERENCES public.category_sections(id) ON DELETE SET NULL;
