-- Cocina multi-día (mockup aprobado 19-07): el día es la unidad de trabajo.
-- 1) Las notas del evento ganan día: cada nota pertenece a un día del evento
--    (null = nota antigua / evento de un solo día → se trata como día 1).
-- 2) Registro de fichas impresas por día: la primera impresión de la ficha
--    de un día lo deja registrado (el desplegable se pinta verde suave).
--    Un día pasado SIN registro delata que operó sin ficha.

ALTER TABLE public.event_kitchen_notes
  ADD COLUMN IF NOT EXISTS day integer;

CREATE TABLE IF NOT EXISTS public.event_day_prints (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL,
  quotation_id uuid NOT NULL REFERENCES public.quotations(id) ON DELETE CASCADE,
  day integer NOT NULL,
  printed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (quotation_id, day)
);
