-- Contactos por cliente — versión mínima (adelanto de la Etapa 4).
-- Solo el nombre por ahora; email, teléfono y cargo llegan en la Etapa 4
-- sobre esta misma tabla, sin rehacer nada. La cotización sigue guardando
-- el NOMBRE como foto (contact_name, migración 33): renombrar o borrar un
-- contacto no reescribe cotizaciones históricas.

CREATE TABLE IF NOT EXISTS public.client_contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id),
  client_id uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT client_contacts_unique UNIQUE (client_id, name)
);

CREATE INDEX IF NOT EXISTS idx_client_contacts_client
  ON public.client_contacts(client_id);

GRANT ALL ON public.client_contacts TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.client_contacts_id_seq
  TO anon, authenticated;
