-- Migración 49 — PORTAL Fase 2b: "Ya transferí" (30-07-2026).
-- El cliente sube su comprobante desde el portal; queda PENDIENTE
-- hasta que el equipo lo confirma en Post-Venta (recién ahí se
-- registra el pago real). La plata nunca se registra sola.

CREATE TABLE IF NOT EXISTS public.portal_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL,
  quotation_id uuid NOT NULL
    REFERENCES public.quotations(id) ON DELETE CASCADE,
  payment_id uuid
    REFERENCES public.payments(id) ON DELETE SET NULL,
  client_contact_id bigint
    REFERENCES public.client_contacts(id) ON DELETE SET NULL,
  file_url text NOT NULL,
  declared_amount numeric NOT NULL,
  -- pendiente | confirmado | rechazado
  status text NOT NULL DEFAULT 'pendiente',
  review_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_portal_receipts_company_status
  ON public.portal_receipts(company_id, status);
