-- Migración 53 — SECCIONES EN SERVICIOS FIJOS (30-07-2026, pedido de
-- Felipe: "ídem que servicios variables"). Secciones libres por
-- empresa + orden arrastrable; un servicio fijo vive en UNA sección
-- (a diferencia de variables, que son multi-categoría).

CREATE TABLE IF NOT EXISTS public.fixed_service_sections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_fixed_sections_company
  ON public.fixed_service_sections(company_id);

-- Lección RLS fase 0: las tablas nuevas no heredan permisos.
GRANT ALL ON TABLE public.fixed_service_sections TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.fixed_service_sections_id_seq
  TO service_role;

ALTER TABLE public.fixed_services
  ADD COLUMN IF NOT EXISTS section_id bigint
    REFERENCES public.fixed_service_sections(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS sort_order integer;
