-- Migración 59 — BITÁCORA COMERCIAL (03-08-2026, "el descreme, no el
-- CRM"). Hilo de notas de seguimiento por cotización: la conversación
-- para VENDER la propuesta, separada del contenido de la propuesta.
-- Ajustes del estudio de mercado (Pipedrive/HubSpot/Close): notas
-- editables/borrables SOLO por su autor (la inmutabilidad castiga el
-- error de tipeo y desincentiva registrar); el autor viaja con nombre
-- congelado al momento de escribir. 100 % aditiva.
CREATE TABLE IF NOT EXISTS public.quotation_followups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz,
  company_id bigint NOT NULL,
  -- quotations.id es uuid (quemadura 03-08: bigint rompe la FK)
  quotation_id uuid NOT NULL
    REFERENCES public.quotations(id) ON DELETE CASCADE,
  author_user_id uuid,
  author_name text,
  note text NOT NULL,
  -- llamada | correo | reunion | whatsapp | otro (valida el backend)
  tipo text,
  next_contact_date date
);

CREATE INDEX IF NOT EXISTS idx_qf_company_quotation
  ON public.quotation_followups(company_id, quotation_id, created_at DESC);
