-- Migración 67 — Un paquete también lleva servicios sueltos
-- 13-08-2026
--
-- EL PROBLEMA (lo pilló Felipe el mismo día que se creó):
-- un paquete solo podía contener MENÚS. Pero un programa real también
-- lleva servicios que NO son un menú — el alojamiento (un servicio,
-- N noches) y la fiesta de despedida (un servicio suelto que se suma a
-- la cena del último día).
--
-- Para meterlos igual hubo que disfrazarlos, y quedaron 6 impostores:
--   · "Sernatur Alojamiento 4/5/6 noches" → menús de UN SOLO servicio
--   · "Sernatur Cena Día 4/5/6 con fiesta" → COPIAS de otro menú + 1
-- El segundo caso es el peligroso: la cena del Día 4 existía dos veces,
-- así que un cambio en la receta o en la composición obligaba a
-- acordarse de tocar las dos, o el paquete empezaba a mentir.
--
-- LA CURA: que el paquete pueda llevar servicios sueltos con su
-- cantidad, igual que un menú lleva los suyos. Con eso el alojamiento
-- entra como servicio × N noches, la fiesta como servicio × 1, y los 6
-- impostores se borran (lo hace el backfill que acompaña).

CREATE TABLE IF NOT EXISTS public.service_group_collection_services (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id bigint NOT NULL
                REFERENCES public.service_group_collections(id) ON DELETE CASCADE,
  variable_service_id bigint NOT NULL
                REFERENCES public.variable_services(id) ON DELETE CASCADE,
  -- Cuántas veces entra el servicio al aplicar el paquete. El
  -- alojamiento de un programa de 4 días entra 4 veces.
  quantity      integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at    timestamptz NOT NULL DEFAULT now(),
  -- Un servicio no se repite dentro del mismo paquete: si hace falta
  -- más de uno, sube la cantidad.
  UNIQUE (collection_id, variable_service_id)
);

-- El acceso se filtra por empresa a través del paquete, igual que
-- service_group_collection_items (que tampoco tiene company_id).
CREATE INDEX IF NOT EXISTS idx_sgcs_collection
  ON public.service_group_collection_services (collection_id);

ALTER TABLE public.service_group_collection_services ENABLE ROW LEVEL SECURITY;
